
<html  lang="en">
	<head>
	    <meta charset="UTF-8">
    
		<title>Blog | Affordable legal Help</title>
		<?php include("libs.php");
		include("config/connect.php");
		?>
		
<!--<base href="https://affordablelegalhelp.com/blog_index.php">-->
	</head>
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "Article",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "Article",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/images/divorce-2755736_640.jpg"
}, {
  "@context" : "http://schema.org",
  "@type" : "Article",
  "name" : "Our Blog We are dedicated to provide the highest level of legal services in United State",
  "image" : "https://affordablelegalhelp.com/images/divorce-2755736_640.jpg"
}, {
  "@context" : "http://schema.org",
  "@type" : "Article",
  "name" : "How Unbundled Legal Services Benefit Divorce Cases",
  "image" : "https://affordablelegalhelp.com/images/divorce-2755736_640.jpg"
}, {
  "@context" : "http://schema.org",
  "@type" : "Article",
  "name" : "What are Unbundled Legal Services?",
  "image" : "https://affordablelegalhelp.com/images/Capture.png"
} ]
</script>
<body>
<?php
include"header.php";
?>

<div class="blog_bg">
	<h1 class="jl_heading font-weight-bold text-white text-center" style="padding-top:120px;">Our Blog</h1>
    <h5 class="heading text-white text-center" style="padding-bottom:120px">We are dedicated to provide the highest <br />level of legal services in United State</h5>
</div>

<div id="searchbox" class="container border-light border-top border-bottom border-right border-left mt-4 p-3 d-block" style="box-shadow:0px 0px 11px 0px #CCCCCC;">
    
    <form action="blog-search-result" method="get" enctype="multipart/form-data">
        <p class="font-weight-bold text-left" style="font-size:18px;">Search Article</p>
        <div class="row">
            <input type="text" class="form-control col-9 mt-0 pt-0 mr-1 ml-2" name="value" placeholder="Search this site" size="25">
            <input type="submit" name="search" class="btn btn-primary col-2" value="Search">
        </div>
    </form>
</div>

<section class="bg-transparent text-dark mt-5">
<div class="container">
    <div class="row">
        
        <div class="col-xl-8 col-lg-8 col-md-8  col-sm-12 col-12  mb-3" >
           
        	<?php 
            // include("config/connect.php");
            $select_posts = "select * from posts order by rand() LIMIT 0,4";
            $run_posts = mysqli_query($con,$select_posts);
            while($row=mysqli_fetch_array($run_posts)){
                $post_id = $row['post_id']; 
                $post_title = $row['post_title'];
                $post_date = $row['post_date'];
                $post_author = $row['post_author'];
                $post_image = $row['post_image'];
                $post_content = $row['post_content'];
            ?>
            
             <div class="card bg-white set_img card h-100 mb-5 " style="border-radius:20px; box-shadow:0px 0px 8px 0px #CCCCCC;">
                <div class="card-body text-dark">
                	<a href="view-blog/<?php echo $post_id; ?>" class="nav-link text-dark pl-0 ml-0">
                    <h2 onmouseover="this.style.color='#959595';" onmouseout="this.style.color='black';">
                    <?php echo $post_title; ?>
                    </h2>
                    </a>
                    
                    
                    <!--<p class="text-black-50 text-left" style="font-size:15px; font-weight:500;">-->
                        <?php
                        // echo $post_date;
                        ?>
                        <!--</p>-->
                    
                    <!--<p align="right">Posted by:&nbsp;&nbsp;<b>-->
                    <?php
                     //echo $post_author; 
                     
                     ?>
                     <!--</b></p>-->
                    
                    <img src="images/<?php echo $post_image; ?>" class="img-fluid"/>
                    <?php
                    // for ($i=0;$i<300;$i++){
                    //     echo $post_content[$i];
                    // }
                    $post_content=strip_tags($post_content);
                    ?>
                    <p  class="text-dark home_heading_settings text-left pt-4 ">
                    <?php 
                    
                    // echo implode(' ', array_slice(explode(' ', $gg), 0, 90));
                    // echo $post_content;
                        echo substr($post_content,0,300);
                    ?>...
                    </p>
                    
                    <p align="left"><a href="view-blog/<?php echo $post_id; ?>" class="btn btn-md btn-outline-info mt-4" style="font-weight:600">
                        Continue Reading <i class="fas fa-chevron-right "></i>
                    </a></p>
                </div>
            </div>
            <?php } ?>
                	 
        </div>
        
        <div class="col-xl-4 col-lg-4 col-md-4  col-sm-12 col-12 mb-3 ">
            <div class="card  bg-white set_img  card h-100 " style="display: table-cell; box-shadow:0px 0px 15px 0px #CCCCCC;">
                <div class="card-body text-dark">
                	
                	<h2 align="left">Recently Uploaded</h2><hr>
                    <?php 
                    
                    $query = "select * from posts order by 1 DESC LIMIT 0,6";
                    
                        $run = mysqli_query($con,$query); 
                        
                        while ($row=mysqli_fetch_array($run)){
                        
                        $post_id = $row['post_id'];
                        $title = $row['post_title'];
                        $image = $row['post_image'];
                        $post_date = $row['post_date'];
                    
                    ?>
                        <div class="row mt-2 p-2">
                            <a href="view-blog/<?php echo $post_id; ?>" class="col-5 d-block mr-0 pr-0">
                            <img src='images/<?php echo $image; ?>' width='100' height='100'></a>
                            
                            <a href="view-blog/<?php echo $post_id; ?>" class="col-7 d-block ml-0 pl-0 pr-0 text-dark nav-link" >
                            <h5 class="font-weight-normal" onmouseover="this.style.color='#959595';" onmouseout="this.style.color='black';">
                            <?php echo $title; ?></h5>
                            <!--<p class="text-left text-black-50">&nbsp;&nbsp;<b>-->
                            <?php
                            // echo $post_date;
                            ?>
                            <!--</b></p>-->
                            </a>
                        
                        </div>
                        
                        
                    <?php } ?>
                	
                </div>
            </div>
        </div>

        
    </div>
</div>
</section>




<?php include("footer.php"); ?>


</body>
</html>