<?php 
session_start();
error_reporting(0);
include_once "config/database.php"; 
include_once "object/login.php";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />
    <!--yandex-->
    <meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<title>Affordable Legal Help | Find Affordable Legal Help with us </title>
<link rel="shortcut icon" type="image/x-icon" href="favicon.png" />

<meta name="description" content="Enjoy Fast Access To Top Family Lawyers Across The US. Connect Now With An Attorney In Your Local Area And Get Your Questions Answered Now.">
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=yes">
<!--#Libraries file#-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>


<style>

ul {
    margin-top: 0px;
    margin-bottom: 1rem;
    background-color: white;
}


li {
    border-bottom: 1px solid rgba(39, 40, 41, 0.2);
    padding: 20px;
}

li:hover {
    background-color:rgba(0,78,103,.2);
}

.paddings{
    padding-top:90px; 
    padding-bottom:90px;
}


</style>
<link href='https://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>

<?php include "libs.php"; ?>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>-->
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" />-->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" /> -->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->

<!--<script async src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>-->
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />-->





<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "FIND The Right Family Lawyer In Your Zip Code",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png",
  "url" : "https://affordablelegalhelp.com/"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Divorce",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Support",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Adoption",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Custody",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Grand Parent's Rights",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>
</head>



<body id="fill" style="font-family:'Trebuchet MS', Helvetica, sans-serif";>
    
<?php include_once "header.php"; ?>


<?php if(isset($_REQUEST['submitbtn']))
{
// $status="2";
// $sql = "UPDATE tblbooking SET Status=:status WHERE  id=:eid";
// $query = $dbh->prepare($sql);
// $query -> bindParam(':status',$status, PDO::PARAM_STR);
// $query-> bindParam(':eid',$eid, PDO::PARAM_STR);
// $query -> execute();
// echo "$o";

}?>
<center>
<section class="ser_top" style="background-image: linear-gradient(rgba(23, 26, 28, 0.7),rgba(20, 21, 21, 0.7)),url(../Image/serbg.jpg);">
    <div class="container-fluid  pt-3"><!--div 0 -->
    	<br />
        <h1 class="pt-5 mt-5 text-white jl_heading home_heading_settings" style="font-weight:500; font-family:'Times New Roman', Times, serif;">FIND The Right Family Lawyer In Your Zip Code</h1>
        
        <p class=" texts text-white font-weight-normal home_heading_settings" style="font-weight:500; ">Rectify your legal issues for as low as 500$-$1500 and receive a free consultation!</p>
        
        <?php 
        	if (isset($_POST['submitbtn'])){}
        ?>
        
        <br>
        <form class="ser_state888 mt-3" method="post" ><!--form a -->
        
            <div class="col-9 pr-0 pl-0"><!--div a -->
            	
            	<div class="row">
                
                    <div class="col-12 col-lg-8 col-md-8 col-sm-12 pr-0 pl-0">
                        <input type="text" name="country" id="country" class="form-control font-weight-normal texts ser_box mt-2"  placeholder="Enter Your City Or Zipcode" autocomplete="off" style="border-radius:0px;"/>
                        
                        <div style=" position: absolute; width:100%; ">
                        <div id="countryList" class="heading font-weight-normal text-left bg-transparent" style="line-height:1.429;" >
                        
                        </div>
                        </div>
                    </div>
                    
                    <div class="col-12 col-lg-4 col-md-4 col-sm-12 pl-0 pr-0" style="position: inherit;">
                        <div  id="btnconnect"><!--div c -->
                            <!--<input type="submit" name="submitbtn" id="btns" value="Connect With Lawyer" class="btn font-weight-bold button_size ser_btn mt-2" style="border-radius:0px;"/>-->
                                <input type="submit" name="submitbtn" id="btns" value="Connect With Lawyer" class="btn btn-danger btn-block  mt-2" style="border-radius:0px; padding: 22px;"/>
                        </div><!--div c -->
                    </div>

                    <?php
 if (isset($_POST['submitbtn'])){
    $_SESSION['city']=$_POST['country'];
    $i=$_SESSION['city'];
    
    $database=new Database();
    $db = $database->getConnection();
    
    //$city1=$_POST['city'];
    $city_state = explode(",", $i);
    $query="SELECT * FROM `city` WHERE `City`='$city_state[0]' AND `State`='$city_state[1]' limit 1";
    $qu= $db->prepare($query);
    $qu->execute();
    $resultt=$qu->fetchAll(PDO::FETCH_OBJ);
    $row = $qu->fetch(PDO::FETCH_ASSOC);
    //$result=mysqli_query($conn,$query);
    //$check=mysqli_num_rows($result);
    
    // if($qu->rowCount() > 0){
    echo "<script type='text/javascript'> document.location = 'Complete-your-request'; </script>";	
    // }
    // else{
        
    //     echo "<script type='text/javascript'>$('#country').css({'border':'1px solid red'});</script>";
    //     echo "<span style='font-size:13px; color:#900;' class='error ml-5'>please enter valid US city</span>";
        
    // }
  }
?>
                    
                </div>
                
                
            </div><!--div a -->
                
                
                
                
        </form><!--form a -->
         
    </div><!--div 0 -->
    
</section>
<hr class="pt-0 mt-0 mb-0 bg-dark" style="border-top: 10px solid rgba(0, 81, 152);" />
</center>


<!--<section class="container-fluid text-center row p-4 ml-0" style="background-color:#e3e3e3;">-->

<!--    <div class="col-lg-4 col-md-4 col-sm-12 col-12 mt-4" style="position: inherit;">-->
<!--        <h3 class=" search_heading_settings heading">Instantly Connect With A Lawyer</h3>-->
<!--        <p class="search_heading_settings text-dark texts">talk to a lawyer in minutes</p>-->
<!--    </div>-->
<!--    <div class="col-lg-4 col-md-4 col-sm-12 col-12 mt-4" style="position: inherit;">-->
<!--        <h3 class=" search_heading_settings heading">Save Up To 80% On Legal Fees</h3>-->
<!--        <p class="search_heading_settings text-dark texts">only pay for the help you need</p>-->
<!--    </div>-->
<!--    <div class="col-lg-4 col-md-4 col-sm-12 col-12 mt-4" style="position: inherit;">-->
<!--        <h3 class=" search_heading_settings heading">Pay As You Go</h3>-->
<!--        <p class="search_heading_settings text-dark texts">don't get locked into an expensive retainer</p>-->
<!--    </div>-->
<!--</section>-->







<section class="container text-center pr-3 pl-3 mr-4 paddings">

    <h2 class=" home_heading_settings font-weight-bold mb-5" style="font-size: 46px;">How It Works</h2>
	
    <div class="row">
    
        <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4">
            <table>
                <tr>
                    <td valign="top" >
                    <i class="fa fa-check-square-o fa-3x pr-2 mt-1 " aria-hidden="true"></i>
                    </td>
                    <td class="d-flex">
                        <div class="card border-0 flex-fill">
                            <div class="card-body pt-0 pl-0">
                                <h4 class="card-title text-dark text-center font-weight-bold home_heading_settings">Complete Your Legal Request</h4>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4">
            <table>
                <tr>
                    <td valign="top" >
                    <i class="fa fa-phone fa-3x  pr-2 mt-1 " aria-hidden="true" ></i>
                    </td>
                    <td class="d-flex">
                        <div class="card border-0 flex-fill">
                            <div class="card-body pt-0 pl-0">
                                <h4 class="card-title text-dark text-center font-weight-bold home_heading_settings" >Immediately Connect With Lawyer In Your Local Area</h4>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4">
            <table>
                <tr>
                    <td valign="top" >
                        <i class="fa fa-usd fa-3x  pr-2 mt-1 " aria-hidden="true"></i>
                    </td>
                    <td class="d-flex">
                        <div class="card border-0 flex-fill">
                            <div class="card-body pt-0 pl-3 mt-1">
                                <h4 class="card-title text-dark text-center font-weight-bold home_heading_settings">Save Time & Money</h4>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        
	</div>
       
</section>





<hr class="m-0" />





<section class="paddings" style="background-color:#F9F9F9;">
    <h3 class="text-center home_heading_settings font-weight-bold" style="font-size: 40px;">Watch Our Two Minute Video</h3>

    <center style="background-color:#F9F9F9;">
    <div class="video1 col-12 col-lg-8 col-md-8 col-sm-8" style="">
        <iframe width="900" height="500" src="https://www.youtube.com/embed/L0B8f7WRW88" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen class="video pb-lg-5 pt-lg-5 pb-md-5 pt-md-5 pt-0 pb-0 container"></iframe>
        <br>
    </div>
    </center>
    
</section>




<hr class="m-0" />




<!--
<section class="container-fluid row p-4 ml-0" style="background-color:#e4eff6;">

    <div class="container col-lg-4 col-md-4 col-sm-4 col-12 block_image">
        <img src="Image/serv.PNG" alt="divorce img" class="images card-img-top rounded-circle" />
    </div>
    <div class="container col-lg-8 col-md-8 col-sm-8 col-12 text-left">
        <h3 class=" home_heading_settings xl_heading">What is Affordable Legal Help?</h3>
        <p class="search_heading_settings texts">Millions of people each year are forced to face legal challenges on their own. Affordable Legal Help is a coalition of experienced and caring lawyers that want to see that problem end. We believe that you shouldn’t ever have to go without legal help simply because it is too expensive and that’s why the attorneys in our network have optimized their services and made them available individually to save you money and protect you from undeserved legal consequences.<br /> We will be at your side to face your case and provide you with quality legal assistance that almost anyone can afford. Call us today for help with your legal challenge and to start working with an attorney that cares about helping--not just money.</b></p>
    </div>
</section>




<center>
<section class="container-fluid text-center pt-3 pb-3 mt-5" style="background-color:#e3e3e3;">
	<h1 class="search_heading_settings mt-4 heading">To Connect With An Affordable Attorney in Your Local Area</h1>
    <input type="button" value="Complete your request now" class="btn p-3 mb-4 buttons font-weight-bold" onclick="document.getElementById('fill').scrollIntoView()"/>
</section>
</center>
-->



<center>
<section class="pr-4 pl-4 text-center bg-white paddings">

    <h2 class="mb-5 home_heading_settings font-weight-bold" style="font-size: 46px;">FIELDS OF EXPERTISE</h2>

    <div class="container-fluid">
        <div class="row">
            <!--to maintain the same height of all cards we use d-flex and flex-fill-->
            <div class="col-xl-4 col-lg-4  col-md-6 col-sm-12 col-12  p-3 d-flex">
                <div class="card bg-light border-0 flex-fill" style="border-radius:0;" >
                    <i class="fas fa-heart-broken fa-4x mt-4"></i>
                    <div class="card-body">
                        <h5 class="card-title font-weight-normal text-dark" style="font-size:31px;">Divorce</h5>
                        <p class="card-text text-black-50" style="font-size:15px;">Going through formal proceedings of filing divorce is extremely frustrating. Highly skilled unbundled lawyers under Affordable legal Help will ensure that your goals and demands are met without breaking your bank.</p>
                        <!-- <a href="#" class="btn btn-lg btn-outline-danger">See Profile</a> -->
                        <input type="button" value="Read More" class="btn btn-lg btn-outline-danger"  onclick="window.location.href='divorce'" style="border-radius:0;" />
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-lg-4  col-md-6 col-sm-12 col-12 p-3 d-flex">
                <div class="card bg-light border-0 flex-fill" style="border-radius:0;" >
                    <i class="fas fa-user-shield fa-4x mt-4"></i>
                    <div class="card-body">
                        <h5 class="card-title font-weight-normal text-dark" style="font-size:31px;">Child Support</h5>
                        <p class="card-text text-black-50" style="font-size:15px;">Paying and getting paid child support can be difficult and tiring. Our lawyers are committed to solving any child support issues as quickly as possible so that the financial future of your family is secured.</p>
                        <!-- <a href="#" class="btn btn-lg btn-outline-danger">See Profile</a> -->
                        <input type="button" value="Read More" class="btn btn-lg btn-outline-danger" onclick="window.location.href='child-support'" style="border-radius:0;" />
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-lg-4  col-md-6 col-sm-12 col-12 p-3 d-flex">
                <div class="card bg-light border-0 flex-fill" style="border-radius:0;" >
                    <i class="fas fa-child fa-4x mt-4"></i>
                    <div class="card-body">
                        <h5 class="card-title font-weight-normal text-dark" style="font-size:31px;">Child Adoption</h5>
                        <p class="card-text text-black-50" style="font-size:15px;">Taking legal and parental rights over a child is an exciting but stressful process. The attorneys we partner with ensure that the specific legal details are taken care of so you can enjoy becoming a parent.</p>
                        <!-- <a href="#" class="btn btn-lg btn-outline-danger">See Profile</a> -->
                        <input type="button" value="Read More" class="btn btn-lg btn-outline-danger" onclick="window.location.href='child-addoption'" style="border-radius:0;" />
                    </div>
                </div>
            </div>

            <div class="col-lg-2 col-md-0 col-sm-0 col-12 p-0 d-flex"></div>

            <div class="col-xl-4 col-lg-4  col-md-6 col-sm-12 col-12 p-3 d-flex">
                <div class="card bg-light border-0 flex-fill" style="border-radius:0;" >
                    <i class="fas fa-users fa-4x mt-4"></i>
                    <div class="card-body">
                        <h5 class="card-title font-weight-normal text-dark" style="font-size:31px;">Child Custody</h5>
                        <p class="card-text text-black-50" style="font-size:15px;">Although children can choose for themselves, but the custody matter is usually decided in the courtroom. Our lawyers will help you inform the judge about the situation and determine the option that is best for your child.</p>
                        <!-- <a href="#" class="btn btn-lg btn-outline-danger">See Profile</a> -->
                        <input type="button" value="Read More" class="btn btn-lg btn-outline-danger" onclick="window.location.href='child-custody'" style="border-radius:0;" />
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-lg-4  col-md-6 col-sm-12 col-12 p-3 d-flex">
                <div class="card bg-light border-0 flex-fill" style="border-radius:0;" >
                    <i class="fas fa-fist-raised fa-4x mt-4"></i>
                    <div class="card-body">
                        <h5 class="card-title font-weight-normal text-dark" style="font-size:31px;">Grand Parent's Rights</h5>
                        <p class="card-text text-black-50" style="font-size:15px;">As grandparents, you have certain rights that should not be taken away from you. With our attorneys, you can be sure that you won't lose these rights and that you will live a secure life.</p>
                        <!-- <a href="#" class="btn btn-lg btn-outline-danger">See Profile</a> -->
                        <input type="button" value="Read More" class="btn btn-lg btn-outline-danger" onclick="window.location.href='grand-parent-rights'" style="border-radius:0;" />
                    </div>
                </div>
            </div>

            <div class="col-lg-2 col-md-0 col-sm-0 col-12 p-0 d-flex"></div>
            

    </div>

</section>
</center>




<hr class="m-0" />





<!--<center>-->
<!--<section class="p-5 text-center text-white-50 bg-secondary services_bg mt-5">-->

<!--                   <h2 class="text-dark pt-4 font-weight-bold xl_heading">FIELDS OF EXPERTISE</h2><hr />-->
    
<!--    <div class="row">-->
<!--        <div class="col-lg-4 col-md-6 col-sm-12 col-12 d-block m-auto">-->
<!--            <div class="d-block text-dark m-auto"><i class="fas fa-heart-broken fa-4x"></i></div>-->
<!--            <p class="xl_heading font-weight-normal text-dark">Divorce</p>-->
<!--            <p class="container texts font-weight-normal text-dark">Going through formal proceedings of filing divorce is extremely frustrating. Highly skilled unbundled lawyers under Affordable legal Help will ensure that your goals and demands are met without breaking your bank.</p>-->
<!--            <hr />-->
<!--     	</div>-->
                
<!--        <div class="col-lg-4 col-md-6 col-sm-12 col-12 d-block m-auto">-->
<!--            <div class="d-block text-dark m-auto"><i class="fas fa-child fa-4x"></i></div>-->
<!--            <p class="xl_heading font-weight-normal text-dark">Child Support</p>-->
<!--            <p class="container texts font-weight-normal text-dark">Paying and getting paid child support can be difficult and tiring. Our lawyers are committed to solving any child support issues as quickly as possible so that the financial future of your family is secured.</p>-->
           
<!--            <hr />-->
<!--        </div>-->
                
<!--        <div class="col-lg-4 col-md-6 col-sm-12 col-12 d-block m-auto">-->
<!--            <div class="d-block text-dark m-auto"><i class="fas fa-baby fa-4x"></i></div>-->
<!--            <p class="xl_heading font-weight-normal text-dark">Child Adoption</p>-->
<!--            <p class="container texts font-weight-normal text-dark">Taking legal and parental rights over a child is an exciting but stressful process. The attorneys we partner with ensure that the specific legal details are taken care of so you can enjoy becoming a parent.</p>-->
            
<!--            <hr />-->
<!--        </div>-->
    	
<!--        <div class="col-lg-2 col-md-0 col-sm-0 col-12 p-0"></div>-->
        
<!--        <div class="col-lg-4 col-md-6 col-sm-12 col-12 d-block m-auto">-->
<!--            <div class="d-block text-dark m-auto"><i class="fas fa-users fa-4x"></i></div>-->
<!--            <p class="xl_heading font-weight-normal text-dark">Child Custody</p>-->
<!--            <p class="container texts font-weight-normal text-dark">Although children can choose for themselves, but the custody matter is usually decided in the courtroom. Our lawyers will help you inform the judge about the situation and determine the option that is best for your child.</p>-->
            
<!--            <hr />-->
<!--        </div>-->
        
<!--        <div class="col-lg-4 col-md-6 col-sm-12 col-12 d-block m-auto">-->
<!--            <div class="d-block text-dark m-auto"><i class="fas fa-fist-raised fa-4x"></i></div>-->
<!--            <p class="xl_heading font-weight-normal text-dark">Grand Parent's Rights</p>-->
<!--            <p class="container texts font-weight-normal text-dark">As grandparents, you have certain rights that should not be taken away from you. With our attorneys, you can be sure that you won't lose these rights and that you will live a secure life.</p>-->
            
<!--            <hr />-->
<!--        </div>-->
        
<!--        <div class="col-lg-2 col-md-0 col-sm-0 col-12 p-0"></div>-->
        
<!--    </div>-->
     	
<!--</section>-->
<!--</center>-->
<!--<hr class="m-0" />-->

<!-- <section class="container-fluid">
    <div class="container text-left bottom_padding p-5">
    	<h2 class="pt-2 mb-5 home_heading_settings jl_heading">Why Choose Our Lawyers?</h2>
        
        <h3 class="mt-2 home_heading_settings text-dark heading">Experienced</h3>
        <p class="text-dark font-weight-normal texts" >Each of the attorneys and firms in our proven network has decades of experience serving other individuals in your area. They can serve a variety of needs and even address the most unique cases.</p>
        
        <h3 class="mt-2 home_heading_settings text-dark heading">Friendly</h3>
        <p class="text-dark font-weight-normal texts " >The lawyers in our network really care about getting you the help that you need while treating you with dignity, respect, and communication every step of the way. If you want an attorney that you’ll like to work with, choose one in our network.</p>
        
        <h3 class="mt-2 home_heading_settings text-dark heading">Affordable</h3>
        <p class="text-dark font-weight-normal texts " >The attorneys in the Affordable Legal Help network live up to their title and are happy to provide legal assistance that can be used by anyone--including those on a tight budget.</p>
      
        <h3 class="mt-2 home_heading_settings text-dark heading">Local</h3>
        <p class="text-dark font-weight-normal texts " >Our network features thousands of attorneys and firms, and you’ll be able to easily connect with one in your area to make communication much easier and faster. </p>
        
        <h3 class="mt-2 home_heading_settings text-dark heading">Accessible</h3>
        <p class="text-dark font-weight-normal texts " >You’ll always be able to get in touch with our attorneys. Our lawyers don’t believe in leaving clients in the dark and they’ll be there to answer your questions and address your concerns whenever the need arises.</p>
        
        <h3 class="mt-2 home_heading_settings text-dark heading">Hard-Working</h3>
        <p class="text-dark font-weight-normal texts " >Our in-network attorneys care about results more than anything. They will fight hard to achieve your desired result and won’t rest until every avenue of legal recourse has been exhausted.</p>
        
        
    </div>
    
</section> -->

<center>

<section class="container-fluid text-center paddings" style="background-color:#F9F9F9;">

    <h2 class=" home_heading_settings font-weight-bold mb-5" style="font-size: 46px;">Why Choose Our Lawyers?</h2>
	
    <div class="row  p-2">
    
        <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4 bg-transparent">
            <table>
                <tr>
                    <td valign="top" >
                        <i class="fas fa-user-tie fa-3x pr-2 mt-1 " aria-hidden="true"></i>
                    </td>
                    <td class="d-flex">
                        <div class="card border-0 bg-transparent flex-fill">
                            <div class="card-body  pt-0 pl-0">
                                <h5 class="card-title font-weight-bold text-dark text-left mb-1" style="font-size:18px;">Experienced</h5>
                                <p class="card-text  text-black-50 text-justify text-left" style="font-size:15px;">Each of the attorneys and firms in our proven network has decades of experience serving other individuals in your area. They can serve a variety of needs and even address the most unique cases.</p>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4">
            <table>
                <tr>
                    <td valign="top" >
                        <i class="fas fa-user-friends fa-3x pr-2 mt-1 " aria-hidden="true"></i>
                    </td>
                    <td class="d-flex">
                        <div class="card border-0 bg-transparent flex-fill">
                            <div class="card-body pt-0 pl-0">
                                <h5 class="card-title font-weight-bold text-dark text-left mb-1" style="font-size:18px;">Friendly</h5>
                                <p class="card-text text-black-50 text-justify text-left" style="font-size:15px;">The lawyers in our network really care about getting you the help that you need while treating you with dignity, respect, and communication every step of the way. If you want an attorney that you’ll like to work with, choose one in our network.</p>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4">
            <table>
                <tr>
                    <td valign="top" >
                        <i class="fa fa-user-plus fa-3x pr-2 mt-1 " aria-hidden="true"></i>
                    </td>
                    <td class="d-flex">
                        <div class="card border-0 bg-transparent flex-fill">
                            <div class="card-body pt-0 pl-0">
                                <h5 class="card-title font-weight-bold text-dark text-left mb-1" style="font-size:18px;">Affordable</h5>
                                <p class="card-text text-black-50 text-justify text-left" style="font-size:15px;">The attorneys in the Affordable Legal Help network live up to their title and are happy to provide legal assistance that can be used by anyone--including those on a tight budget.</p>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4">
            <table>
                <tr>
                    <td valign="top" >
                        <i class="fas fa-street-view fa-3x pr-2 mt-1 " aria-hidden="true"></i>
                    </td>
                    <td class="d-flex">
                        <div class="card border-0 bg-transparent flex-fill">
                            <div class="card-body pt-0 pl-0">
                                <h5 class="card-title font-weight-bold text-dark text-left mb-1" style="font-size:18px;">Local</h5>
                                <p class="card-text text-black-50 text-justify text-left" style="font-size:15px;">Our network features thousands of attorneys and firms, and you’ll be able to easily connect with one in your area to make communication much easier and faster. </p>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4">
            <table>
                <tr>
                    <td valign="top" >
                        <!--<i class="fas fa-users fa-3x pr-2 mt-1 " aria-hidden="true"></i>-->
                        <i class="fab fa-accessible-icon fa-3x pr-2 mt-1 " aria-hidden="true"></i>

                    </td>
                    <td class="d-flex">
                        <div class="card border-0 bg-transparent flex-fill">
                            <div class="card-body pt-0 pl-0">
                                <h5 class="card-title font-weight-bold text-dark text-left mb-1" style="font-size:18px;">Accessible</h5>
                                <p class="card-text text-black-50 text-justify text-left" style="font-size:15px;">You’ll always be able to get in touch with our attorneys. Our lawyers don’t believe in leaving clients in the dark and they’ll be there to answer your questions and address your concerns whenever the need arises.</p>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4">
            <table>
                <tr>
                    <td valign="top" >
                        <i class="fas fa-users-cog fa-3x pr-2 mt-1 " aria-hidden="true"></i>
                    </td>
                    <td class="d-flex">
                        <div class="card border-0 bg-transparent flex-fill">
                            <div class="card-body pt-0 pl-0">
                                <h5 class="card-title font-weight-bold text-dark text-left mb-1" style="font-size:18px;">Hard-Working</h5>
                                <p class="card-text text-black-50 text-justify text-left" style="font-size:15px;">Our in-network attorneys care about results more than anything. They will fight hard to achieve your desired result and won’t rest until every avenue of legal recourse has been exhausted.</p>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        
	</div>
       
</section>
</center>




<hr class="m-0" />





<center>
<section class="container-fluid paddings">

    <h2 class="pt-4 mb-5 home_heading_settings font-weight-bold" style="font-size: 46px;">What people are saying</h2>

    <div class="row">

        <div class="col-xl-4 col-lg-4  col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card border-0 flex-fill">
                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5">
                    <img src="Image/default.PNG" class="img-thumbnail border-0 rounded-circle" style="padding: 0px 100px 0px 100px" alt="Responsive image">
                </div>
                <div class="card-body">
                    <h5 class="card-title font-weight-normal text-primary" style="font-size:17px;">SEAN WALKER</h5>
                    <hr>
                    <p class="card-text text-black-50" style="font-size:14px;">"This company rocks. Before them I was quoted over $3000.00 to take my case. "Affordable Legal Help" offered me a couple different programs where I ended up saving about $1000. Thank you for your help in finalizing my divorce."</p>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-lg-4  col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card border-0 flex-fill">
                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5">
                    <img src="Image/default.PNG" class="img-thumbnail border-0 rounded-circle" style="padding: 0px 100px 0px 100px" alt="Responsive image">
                </div>
                <div class="card-body">
                    <h5 class="card-title font-weight-normal text-primary" style="font-size:17px;">JOHN HANNIGAN</h5>
                    <hr>
                    <p class="card-text text-black-50" style="font-size:14px;">“Affordable Legal Help’s unbundled attorneys were the only source of legal help that could help me immediately. I was worried that their service would cost me immensely in the longer term, but I was pleasantly surprised to find such great legal advice at such a reasonable rate. He went above and beyond and did everything he could to ensure a great outcome. I couldn’t have asked for a better law firm or attorney. Thanks guys!!!”</p>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-lg-4  col-md-6 col-sm-12 col-12 p-3 d-flex">
            <div class="card border-0 flex-fill">
                <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5">
                    <img src="Image/default.PNG" class="img-thumbnail border-0 rounded-circle" style="padding: 0px 100px 0px 100px" alt="Responsive image">
                </div>
                <div class="card-body">
                    <h5 class="card-title font-weight-normal text-primary" style="font-size:17px;">ANGELA COLLINS</h5>
                    <hr>
                    <p class="card-text text-black-50" style="font-size:14px;">“At the suggestion of my sister, I contacted the Affordable Legal Help and scheduled a consultation so that I could start the child adoption procedure. They clarified the entire process and gave me all the information I needed to start the process on my own. I feel like I have gotten the best bang for my buck at Affordable Legal Help, and my adoption case is in court right now.”</p>
                </div>
            </div>
        </div>

        <!--<div class="col-xl-4 col-lg-4  col-md-6 col-sm-12 col-12 p-3 d-flex">-->
        <!--    <div class="card border-0 flex-fill">-->
        <!--        <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5">-->
        <!--            <img src="Image/default.PNG" class="img-thumbnail border-0 rounded-circle" style="padding: 0px 100px 0px 100px" alt="Responsive image">-->
        <!--        </div>-->
        <!--        <div class="card-body">-->
        <!--            <h5 class="card-title font-weight-normal text-primary" style="font-size:17px;">NATHAN STARKS</h5>-->
        <!--            <hr>-->
        <!--            <p class="card-text text-dark" style="font-size:14px;">“As an entrepreneur, I have had my share of experience the legal world. I have seen law firms that exploit their customers just to make a quick buck. This made me a little hesitant when assessing my options in a fight for custody of my son. However, upon a few interactions with the unbundled lawyers I connected with through Affordable Legal Help, I knew that I had found the perfect fit for me.”</p>-->
        <!--        </div>-->
        <!--    </div>-->
        <!--</div>-->

        <!--<div class="col-xl-4 col-lg-4  col-md-6 col-sm-12 col-12 p-3 d-flex">-->
        <!--    <div class="card border-0 flex-fill">-->
        <!--        <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5">-->
        <!--            <img src="Image/default.PNG" class="img-thumbnail border-0 rounded-circle" style="padding: 0px 100px 0px 100px" alt="Responsive image">-->
        <!--        </div>-->
        <!--        <div class="card-body">-->
        <!--            <h5 class="card-title font-weight-normal text-primary" style="font-size:17px;">GINA TEAGUE</h5>-->
        <!--            <hr>-->
        <!--            <p class="card-text text-dark" style="font-size:14px;">"I am pleased with your firm’s service and everything has been answered in a timely manner. I appreciate having your firm handle my case; they have put my mind at ease. I would absolutely recommend your firm to family and friends."</p>-->
        <!--        </div>-->
        <!--    </div>-->
        <!--</div>-->

        <!--<div class="col-xl-4 col-lg-4  col-md-6 col-sm-12 col-12 p-3 d-flex">-->
        <!--    <div class="card border-0 flex-fill">-->
        <!--        <div class="pl-lg-3 pr-lg-3 pl-md-4 pr-md-4 pl-sm-5 pr-sm-5">-->
        <!--            <img src="Image/default.PNG" class="img-thumbnail border-0 rounded-circle" style="padding: 0px 100px 0px 100px" alt="Responsive image">-->
        <!--        </div>-->
        <!--        <div class="card-body">-->
        <!--            <h5 class="card-title font-weight-normal text-primary" style="font-size:17px;">MICHAEL SMITH</h5>-->
        <!--            <hr>-->
        <!--            <p class="card-text text-dark" style="font-size:14px;">"Affordable legal Help" did an outstanding work on my case. They were very prompt in responding to my emails and phone calls. If I ever have another problem where I need legal service, I will be contacting your office for representation. Thanks for your help with everything."</p>-->
        <!--        </div>-->
        <!--    </div>-->
        <!--</div>-->

    </div>

    <input type="button" value="Read All Stories" class="btn btn-lg btn-outline-danger mt-3" onclick="window.location.href='success-stories'" style="border-radius:0;" />

</section>
</center>





<hr class="m-0" />





<!-- <section class="bg-white" style="margin: 10% 0% 10% 0%;">

    <h2 class="text-dark text-center font-weight-bold xl_heading">What people are saying</h2>
	
    <center>
    <div class="container-fluid pt-3">
    <div class="carousel slide" id="myslide" >
    
    	<div class="carousel-inner">
            
            <div class="carousel-item active">
                <p class="xs_texts text-black-50 font-weight-normal font-italic" style="width:60%;">
                	"This company rocks. Before them I was quoted over $3000.00 to take my case. "Affordable Legal Help" offered me a couple different programs where I ended up saving about $1000. Thank you for your help in finalizing my divorce."
                </p>
                <h4 class="font-weight-light texts mt-3">SEAN WALKER</h4>
       		</div>
            <div class="carousel-item">
                <p class="xs_texts text-black-50 font-weight-normal font-italic" style="width:60%;">
                	 “Affordable Legal Help’s unbundled attorneys were the only source of legal help that could help me immediately. I was worried that their service would cost me immensely in the longer term, but I was pleasantly surprised to find such great legal advice at such a reasonable rate. He went above and beyond and did everything he could to ensure a great outcome. I couldn’t have asked for a better law firm or attorney. Thanks guys!!!”
                </p>
                <h4 class="font-weight-light texts mt-3">JOHN HANNIGAN</h4>
       		</div>
            <div class="carousel-item">
                <p class="xs_texts text-black-50 font-weight-normal font-italic" style="width:60%;">
                	“At the suggestion of my sister, I contacted the Affordable Legal Help and scheduled a consultation so that I could start the child adoption procedure. They clarified the entire process and gave me all the information I needed to start the process on my own. I feel like I have gotten the best bang for my buck at Affordable Legal Help, and my adoption case is in court right now.”
                </p>
                <h4 class="font-weight-light texts mt-3">ANGELA COLLINS</h4>
       		</div>
            <div class="carousel-item">
                <p class="xs_texts text-black-50 font-weight-normal font-italic" style="width:60%;">
                	“As an entrepreneur, I have had my share of experience the legal world. I have seen law firms that exploit their customers just to make a quick buck. This made me a little hesitant when assessing my options in a fight for custody of my son. However, upon a few interactions with the unbundled lawyers I connected with through Affordable Legal Help, I knew that I had found the perfect fit for me.”
                </p>
                <h4 class="font-weight-light texts mt-3">NATHAN STARKS</h4>
       		</div>
            <div class="carousel-item">
                <p class="xs_texts text-black-50 font-weight-normal font-italic" style="width:60%;">
                	"I am pleased with your firm’s service and everything has been answered in a timely manner. I appreciate having your firm handle my case; they have put my mind at ease. I would absolutely recommend your firm to family and friends.
                </p>
                <h4 class="font-weight-light texts mt-3">GINA TEAGUE</h4>
       		</div>
            <div class="carousel-item">
                <p class="xs_texts text-black-50 font-weight-normal font-italic" style="width:60%;">
                	Affordable legal Help" did an outstanding work on my case. They were very prompt in responding to my emails and phone calls. If I ever have another problem where I need legal service, I will be contacting your office for representation. Thanks for your help with everything."
                </p>
                <h4 class="font-weight-light texts mt-3">MICHAEL SMITH</h4>
       		</div>
            
        </div>
        
        <a href="#myslide" data-slide="prev" class="carousel-control-prev" style="width:6%; background-color: #cdd2d7 !important;">
        	<span class="carousel-control-prev-icon"></span>	
        </a>
        <a href="#myslide" data-slide="next" class="carousel-control-next" style="width:6%; background-color: #cdd2d7 !important;">
        	<span class="carousel-control-next-icon".></span>
        </a>
    </div>
    </div>
    </center>
</section>

-->


<center>
<section class="container-fluid pr-3 pl-3 text-center paddings" style="background-color:#F9F9F9;">
	<h1 class="home_heading_settings font-weight-bold" style="font-size: 46px;">Press Release</h1>
    <center><p class=" mb-0 col-2 " style="border-top: 5px solid rgba(0, 81, 152);"></p></center>
    
    <center>
    <p class="text-center font-weight-bold home_heading_settings col-lg-7 mt-5 mb-5" style="font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;">Although legal assistance solves one problem, it creates another, i.e. the financial issues. Legal assistance has always been one of the most expensive services in America to the extent that many people would rather forego a family matter rather than invest in hiring a good lawyer.
    </p>
    </center>
    
    <!-- <input type="button" value="Read More" onclick="window.location.href='press-release'" class="btn p-2 btn-md mb-4 buttons font-weight-normal"/> -->
    <input type="button" value="Read More" class="btn btn-lg btn-outline-danger mt-4" onclick="window.location.href='press-release'" style="border-radius:0;" />
</section>
</center>






<hr class="m-0" />






<center>
<section class=" paddings bg-white" >
<div class="container text-center">

    <h2 class="home_heading_settings font-weight-bold" style="font-size: 46px;">Our Blog</h2>

    <center>
    <p  class="text-dark texts font-weight-normal mb-2 col-lg-8" style="font-weight:500;">
    Unbundling or A-La-Carte Services is gaining popularity among both attorneys and the public.
    </p>
    </center>

    <div class="container-fluid">

        <div class="row">

            <div class="col-xl-4 col-lg-4  col-md-6 col-sm-12 col-12  p-3 d-flex">
                <div class="card bg-white flex-fill" style="box-shadow: 0px 0px 15px 0px #CCCCCC;">

                    <div class="card-body">

                        <div class="card-title">

                            <a href="view-blog?id=<?php echo 30; ?>" class="nav-link text-dark pl-0 ml-0">
                                <h5 class="font-weight-normal text-left" onmouseover="this.style.color='#959595';" onmouseout="this.style.color='black';" style="font-size:22px;">
                                How Unbundled Legal Services Benefit Divorce Cases
                                </h5>
                            </a>

                        </div>

                        <p class="card-text text-black-50 text-left"  style='font-size:17px;'>
                            Going through a divorce is a challenging, painful, transforming, and expensive experience.  It is not something that anyone wants to go through but there are times when it becomes necessary in order to end a failed, sometimes even abusive, marriage and move on.  Depending on factors like the money and property involved, disputes over custody of children, and the attitude of the parties, it can be a long, messy process...
                            <br/>
                            <a href="view-blog?id=<?php echo 30; ?>" class="font-weight-bold">read more</a>
                        </p>

                        
                    </div>
                </div>
            </div>



            <?php 
            include("config/connect.php");
            $select_posts = "select * from posts order by rand() LIMIT 0,4";
            $run_posts = mysqli_query($con,$select_posts);
            while($row=mysqli_fetch_array($run_posts)){
                $post_id = $row['post_id']; 
                $post_title = $row['post_title'];
                $post_date = $row['post_date'];
                $post_author = $row['post_author'];
                $post_image = $row['post_image'];
                $post_content = $row['post_content'];
                $post_content = substr($post_content,0,400);
            ?>

            
            <div class="col-xl-4 col-lg-4  col-md-6 col-sm-12 col-12  p-3 d-flex">
                <div class="card bg-white flex-fill"  style="box-shadow: 0px 0px 15px 0px #CCCCCC;">

                    <div class="card-body">

                        <div class="card-title">

                            <a href="view-blog?id=<?php echo $post_id; ?>" class="nav-link text-dark pl-0 ml-0">
                                <h5 class="font-weight-normal text-left" onmouseover="this.style.color='#959595';" onmouseout="this.style.color='black';" style="font-size:22px;">
                                    <?php echo $post_title; ?>
                                </h5>
                            </a>

                        </div>

                        <div class="card-text">

                            <?php  
                                if ($post_id == 30 ) {
                                    echo "<p class='card-text text-black-50 text-left' style='font-size:17px;'>Going through a divorce is a challenging, painful, transforming, and expensive experience.  It is not something that anyone wants to go through but there are times when it becomes necessary in order to end a failed, sometimes even abusive, marriage and move on.  Depending on factors like the money and property involved, disputes over custody of children, and the attitude of the parties, it can be a long, messy process...</p>"; 
                                } elseif ($post_id == 29) {
                                    echo "<p class='card-text text-black-50 text-left' style='font-size:17px;'>Finding the right lawyer can seem like a daunting task.  At Affordable Legal Help we understand that, when you are faced with a legal issue and need help, you want to find an experienced, professional attorney who can handle your specific case.  Much like finding the right doctor to treat you when you are ill, finding the right lawyer to take your case means placing your trust in the wisdom and knowledge of a professional in a difficult time...</p>"; 
                                } else {
                                    echo "<p class='card-text text-black-50 text-left' style='font-size:17px;'>Finding the right lawyer can seem like a daunting task.  At Affordable Legal Help we understand that, when you are faced with a legal issue and need help, you want to find an experienced, professional attorney who can handle your specific case.  Much like finding the right doctor to treat you when you are ill, finding the right lawyer to take your case means placing your trust in the wisdom and knowledge of a professional in a difficult time...</p>"; 
                                }
                            ?>

                        </div>

                        <p align="left">
                            <a href="view-blog?id=<?php echo $post_id; ?>" class="font-weight-bold">read more</a>
                        </p>
                        
                    </div>
                </div>
            </div>

            <?php } ?>
        </div>

    </div>


    <input type="button" value="Read More" class="btn btn-lg btn-outline-danger mt-3" onclick="window.location.href='our-blog'" style="border-radius:0;" />

</div>
</section>
</center>






<hr class="m-0" />





<center>
<section class="container-fluid text-center paddings"  style="background-color:#F9F9F9;">
	<h3 class="home_heading_settings font-weight-bold">To Connect With An Affordable Attorney in Your Local Area</h3>
    <input type="button" value="Complete your request now" class="btn btn-lg p-3 btn-outline-danger" onclick="document.getElementById('fill').scrollIntoView()" style="border-radius:0;" />
</section>
</center>

<?php include_once"footer.php"; ?>


</body>
</html>


<script>

$(document).ready(function(){
   

$('#country').keyup(function(){
   
    var query=$(this).val();
    // if (query>=44101 && query<=44199){
    //     query="Cleveland,OH";
    // }
    // else if ((query>=45401 &&query<=45406)||(query>=45409 && query<=45417)||(query>=45419 && query<=45420)||(query>=45422 && query<=45424)||(query>=45428 && query<=45435)||(query>=45439 && query<=45441)||(query>=45448 && query<=45449)||(query>=45458 && query<=45459)||(query>=45469 && query<=45470)||(query>=45481 && query<=45482)||query==45490||query==45479||query==45475||query==45437||query==45426||query==45390){
    //     query="Dayton,OH";
    // }
    // else if (query>=43201 && query<=43270){
    //     query="Columbus,OH";
    // }
    // else if (query>=45201 && query<=45299){
    //     query="Cincinnati,OH";
    // }
    if (query !=''){
       $.ajax({
   url:"object/search.php",
   method:"POST",
   data:{query:query},
   success:function(data){
       $('#countryList').fadeIn();
       $('#countryList').html(data);
       

   }
       });

    }
    else{
        $('#countryList').fadeOut();
        $('#countryList').html("");
    }
});
$(document).on('click','li',function(){
    $('#country').val($(this).text());
    $('#countryList').fadeOut();
});
});

</script>
