<?php 
session_start();
error_reporting(0);
include_once "config/database.php"; 
include_once "object/login.php";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />
    <!--yandex-->
    <meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<title>Affordable Legal Help | Find Affordable Legal Help with us </title>
<link rel="shortcut icon" type="image/x-icon" href="favicon.png" />

<meta name="description" content="Enjoy Fast Access To Top Family Lawyers Across The US. Connect Now With An Attorney In Your Local Area And Get Your Questions Answered Now.">
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=yes">
<!--#Libraries file#-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>


<style>

ul {
    margin-top: 0px;
    margin-bottom: 1rem;
    background-color: white;
}


li {
    border-bottom: 1px solid rgba(39, 40, 41, 0.2);
    padding: 20px;
}

li:hover {
    background-color:rgba(0,78,103,.2);
}

.paddings{
    padding-top:90px; 
    padding-bottom:90px;
}


</style>
<link href='https://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>

<?php include "libs.php"; ?>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>-->
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" />-->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" /> -->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->

<!--<script async src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>-->
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />-->





<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "FIND The Right Family Lawyer In Your Zip Code",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png",
  "url" : "https://affordablelegalhelp.com/"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Divorce",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Support",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Adoption",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Custody",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Grand Parent's Rights",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>
</head>



<body id="fill" style="font-family:'Trebuchet MS', Helvetica, sans-serif";>
    
<?php include_once "header.php"; ?>


<?php if(isset($_REQUEST['submitbtn']))
{
// $status="2";
// $sql = "UPDATE tblbooking SET Status=:status WHERE  id=:eid";
// $query = $dbh->prepare($sql);
// $query -> bindParam(':status',$status, PDO::PARAM_STR);
// $query-> bindParam(':eid',$eid, PDO::PARAM_STR);
// $query -> execute();
// echo "$o";

}?>
<center>
<section class="ser_top" style="background-image: linear-gradient(rgba(23, 26, 28, 0.7),rgba(20, 21, 21, 0.7)),url(../Image/serbg.jpg);">
    <div class="container-fluid  pt-3"><!--div 0 -->
    	<br />
        <h1 class="pt-5 mt-5 text-white jl_heading home_heading_settings" style="font-weight:500; font-family:'Times New Roman', Times, serif;">FIND The Right Family Lawyer In Your Zip Code</h1>
        
        <p class=" texts text-white font-weight-normal home_heading_settings" style="font-weight:500; ">Rectify your legal issues for as low as 500$-$1500 and receive a free consultation!</p>
        
        <?php 
        	if (isset($_POST['submitbtn'])){}
        ?>
        
        <br>
        <form class="ser_state888 mt-3" method="post" ><!--form a -->
        
            <div class="col-9 pr-0 pl-0"><!--div a -->
            	
            	<div class="row">
                
                    <div class="col-12 col-lg-8 col-md-8 col-sm-12 pr-0 pl-0">
                        <input type="text" name="country" id="country" class="form-control font-weight-normal texts ser_box mt-2"  placeholder="Enter Your City Or Zipcode" autocomplete="off" style="border-radius:0px;"/>
                        
                        <div style=" position: absolute; width:100%; ">
                        <div id="countryList" class="heading font-weight-normal text-left bg-transparent" style="line-height:1.429;" >
                        
                        </div>
                        </div>
                    </div>
                    
                    <div class="col-12 col-lg-4 col-md-4 col-sm-12 pl-0 pr-0" style="position: inherit;">
                        <div  id="btnconnect"><!--div c -->
                            <!--<input type="submit" name="submitbtn" id="btns" value="Connect With Lawyer" class="btn font-weight-bold button_size ser_btn mt-2" style="border-radius:0px;"/>-->
                                <input type="submit" name="submitbtn" id="btns" value="Connect With Lawyer" class="btn btn-danger btn-block  mt-2" style="border-radius:0px; padding: 22px;"/>
                        </div><!--div c -->
                    </div>

                    <?php
 if (isset($_POST['submitbtn'])){
    $_SESSION['city']=$_POST['country'];
    $i=$_SESSION['city'];
    
    $database=new Database();
    $db = $database->getConnection();
    
    //$city1=$_POST['city'];
    $city_state = explode(",", $i);
    $query="SELECT * FROM `city` WHERE `City`='$city_state[0]' AND `State`='$city_state[1]' limit 1";
    $qu= $db->prepare($query);
    $qu->execute();
    $resultt=$qu->fetchAll(PDO::FETCH_OBJ);
    $row = $qu->fetch(PDO::FETCH_ASSOC);
    //$result=mysqli_query($conn,$query);
    //$check=mysqli_num_rows($result);
    
    // if($qu->rowCount() > 0){
    echo "<script type='text/javascript'> document.location = 'Complete-your-request'; </script>";	
    // }
    // else{
        
    //     echo "<script type='text/javascript'>$('#country').css({'border':'1px solid red'});</script>";
    //     echo "<span style='font-size:13px; color:#900;' class='error ml-5'>please enter valid US city</span>";
        
    // }
  }
?>
                    
                </div>
                
                
            </div><!--div a -->
                
                
                
                
        </form><!--form a -->
         
    </div><!--div 0 -->
    
</section>
<hr class="pt-0 mt-0 mb-0 bg-dark" style="border-top: 10px solid rgba(0, 81, 152);" />
</center>

<section class="container-fluid m-0 pt-5 pb-5 row">

    <section class="container col-lg-3 col-md-3 col-sm-12 col-12">
        <input type="button" value="Divorce" class="btn btn-lg btn-block btn-outline-danger m-0" onclick="window.location.href='our-services'" style="border-radius:0;" />
        <input type="button" value="Child Support" class="btn btn-lg btn-block btn-outline-danger m-0" onclick="window.location.href='our-services'" style="border-radius:0;" />
        <input type="button" value="Child Addoption" class="btn btn-lg btn-block btn-outline-danger m-0" onclick="window.location.href='our-services'" style="border-radius:0;" />
        <input type="button" value="Child Custody" class="btn btn-lg btn-block btn-outline-danger m-0" onclick="window.location.href='our-services'" style="border-radius:0;" />
        <input type="button" value="Grand Parent's Rights" class="btn btn-lg btn-block btn-outline-danger m-0" onclick="window.location.href='our-services'" style="border-radius:0;" />
    
        <div class="jumbotron jumbotron-fluid d-flex align-items-center contactUs_bg1 mt-5" style="border-radius:0; height:300px;">
            <div class="container">
                <h2 class="text-white text-left ">Need Help?</h2>  
                <p class="text-white divorce_font">Towards the viewer. Gregor then turned to look out the window at the dull weather. Drops look out the</p>
                <input type="button" value="Contact Us" class="btn btn-sm btn-success" onclick="window.location.href='contact-us'" />
            </div>
        </div>

    </section>
    
    
   
    <section class="col-lg-8 col-md-9 col-sm-12 col-12">

        <h1 class="text-dark pt-4 font-weight-normal mb-3" >Child Support</h1>
        <p class=" text-dark divorce_font" >Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
        <img src="Image/est1.jpg" class="img-fluid mt-4 mb-4" alt="divorce image">
        <p class=" text-dark divorce_font" >Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>

        <div class="container-fluid mt-5 mb-5">
            <div class="row"  style="box-shadow: 0px 0px 15px 0px #CCCCCC;">
                <div class="col-xl-4 col-lg-4  col-md-4 col-sm-12 col-12 p-0  d-flex">
                    <div class="card bg-light flex-fill" style="border-radius:0;" >
                        <div class="card-body">
                            <i class="fas fa-user fa-4x mt-4 mb-2"></i>
                            <h3 class="card-title font-weight-normal text-dark ">Lorem</h3>
                            <p class="card-text text-black-50 divorce_font">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                </div>

                <div class="col-xl-4 col-lg-4  col-md-4 col-sm-12 col-12 p-0 d-flex">
                    <div class="card bg-light  flex-fill" style="border-radius:0;" >
                        <div class="card-body">
                            <i class="fas fa-user fa-4x mt-4 mb-2"></i>
                            <h3 class="card-title font-weight-normal text-dark ">Lorem</h3>
                            <p class="card-text text-black-50 divorce_font">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                </div>

                <div class="col-xl-4 col-lg-4  col-md-4 col-sm-12 col-12 p-0 d-flex">
                    <div class="card bg-light  flex-fill" style="border-radius:0;" >
                        <div class="card-body">
                            <i class="fas fa-user fa-4x mt-4 mb-2"></i>
                            <h3 class="card-title font-weight-normal text-dark">Lorem</h3>
                            <p class="card-text text-black-50 divorce_font">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <h3 class="text-dark pt-4 font-weight-normal mb-3" >Benefit Of This Service</h3>
        <p class=" text-dark divorce_font">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
        
        <div class="row">
            <div class="col-xl-6 col-lg-6  col-md-6 col-sm-12 col-12 p-0">
                <ul class="list-group">

                    <li class="list-group-item border-0">
                        <table>
                        <tr class="d-flex align-items-top">
                            <td><i class="fa fa-check fa-1x pr-2 pt-1  " aria-hidden="true"></i></td>
                            <td class=" divorce_font">Lorem ipsum dolor sit amet, consectetur adipiscing elit,</td>
                        </tr>
                        </table>
                    </li>
                    <li class="list-group-item border-0">
                        <table>
                        <tr class="d-flex align-items-top">
                            <td><i class="fa fa-check fa-1x pr-2 pt-1  " aria-hidden="true"></i></td>
                            <td class=" divorce_font">Lorem ipsum dolor sit amet, consectetur adipiscing elit,</td>
                        </tr>
                        </table>
                    </li>
                    <li class="list-group-item border-0">
                        <table>
                        <tr class="d-flex align-items-top">
                            <td><i class="fa fa-check fa-1x pr-2 pt-1  " aria-hidden="true"></i></td>
                            <td class=" divorce_font">Lorem ipsum dolor sit amet, consectetur adipiscing elit,</td>
                        </tr>
                        </table>
                    </li>
                    <!-- <li class="list-group-item border-0"><i class="fas fa-check text-info mx-2"></i>Lorem ipsum dolor sit amet, consectetur adipiscing elit,</li> -->
                    
                </ul>
            </div>

            <div class="col-xl-6 col-lg-6  col-md-6 col-sm-12 col-12 p-0">
                <ul class="list-group">

                    <li class="list-group-item border-0">
                        <table>
                        <tr class="d-flex align-items-top">
                            <td><i class="fa fa-check fa-1x pr-2 pt-1  " aria-hidden="true"></i></td>
                            <td class=" divorce_font">Lorem ipsum dolor sit amet, consectetur adipiscing elit,</td>
                        </tr>
                        </table>
                    </li>
                    <li class="list-group-item border-0">
                        <table>
                        <tr class="d-flex align-items-top">
                            <td><i class="fa fa-check fa-1x pr-2 pt-1  " aria-hidden="true"></i></td>
                            <td class=" divorce_font">Lorem ipsum dolor sit amet, consectetur adipiscing elit,</td>
                        </tr>
                        </table>
                    </li>
                    <li class="list-group-item border-0">
                        <table>
                        <tr class="d-flex align-items-top">
                            <td><i class="fa fa-check fa-1x pr-2 pt-1  " aria-hidden="true"></i></td>
                            <td class=" divorce_font">Lorem ipsum dolor sit amet, consectetur adipiscing elit,</td>
                        </tr>
                        </table>
                    </li>
                    <!-- <li class="list-group-item border-0"><i class="fas fa-check text-info mx-2"></i>Lorem ipsum dolor sit amet, consectetur adipiscing elit,</li> -->
                    
                </ul>
            </div>
        </div>

        <h3 class="text-dark pt-4 font-weight-normal mb-3" >Research</h3>
        <p class=" text-dark divorce_font">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
        
    </section>


</section>




<?php include_once"footer.php"; ?>


</body>
</html>


<script>

$(document).ready(function(){
   

$('#country').keyup(function(){
   
    var query=$(this).val();
    // if (query>=44101 && query<=44199){
    //     query="Cleveland,OH";
    // }
    // else if ((query>=45401 &&query<=45406)||(query>=45409 && query<=45417)||(query>=45419 && query<=45420)||(query>=45422 && query<=45424)||(query>=45428 && query<=45435)||(query>=45439 && query<=45441)||(query>=45448 && query<=45449)||(query>=45458 && query<=45459)||(query>=45469 && query<=45470)||(query>=45481 && query<=45482)||query==45490||query==45479||query==45475||query==45437||query==45426||query==45390){
    //     query="Dayton,OH";
    // }
    // else if (query>=43201 && query<=43270){
    //     query="Columbus,OH";
    // }
    // else if (query>=45201 && query<=45299){
    //     query="Cincinnati,OH";
    // }
    if (query !=''){
       $.ajax({
   url:"object/search.php",
   method:"POST",
   data:{query:query},
   success:function(data){
       $('#countryList').fadeIn();
       $('#countryList').html(data);
       

   }
       });

    }
    else{
        $('#countryList').fadeOut();
        $('#countryList').html("");
    }
});
$(document).on('click','li',function(){
    $('#country').val($(this).text());
    $('#countryList').fadeOut();
});
});

</script>
