<?php 
session_start();
error_reporting(0);
include_once "config/database.php"; 
include_once "object/login.php";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />
    <!--yandex-->
    <meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<title>Success Stories | Find Affordable Legal Help with us </title>
<link rel="shortcut icon" type="image/x-icon" href="favicon.png" />

<meta name="description" content="Enjoy Fast Access To Top Family Lawyers Across The US. Connect Now With An Attorney In Your Local Area And Get Your Questions Answered Now.">
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=yes">
<!--#Libraries file#-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>


<style>

#form32{
	display:none;
}

#head1{
	display:none;
}

li {
    border-bottom: 0px solid rgba(39, 40, 41, 0.2);
    padding: 0px;
}

ul {
    padding: 20px;
}




.divorce_ser{
    background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url("../Image/contactus1.jpg");
    background-size: 100% 100%;
	background-repeat: no-repeat;
	width:100%;
	height:440px;
}

.divorce_font{
	font-size:15px; 
	font-family: 'Muli', sans-serif; 
	line-height:1.7rem;
}




div.stars {
  display: inline-block;
}

input.star { display: none; }

label.star {
  float: right;
  padding: 1px;
  font-size: 20px;
  color: #444;
  /* transition: all .1s; */
}

input.star:checked ~ label.star:before {
  content: '\f005';
  color: #FD4;
  /* transition: all .15s; */
}

input.star-5:checked ~ label.star:before {
  color: #FE7;
  /* text-shadow: 0 0 20px #952; */
}

input.star-1:checked ~ label.star:before { color: #F62; }

label.star:hover { transform: rotate(-10deg) scale(1.3); }

label.star:before {
  content: '\f006';
  font-family: FontAwesome;
}


</style>



<link href='https://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>

<?php include "libs.php"; ?>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>-->
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" />-->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" /> -->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->

<!--<script async src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>-->
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />-->





<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "FIND The Right Family Lawyer In Your Zip Code",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png",
  "url" : "https://affordablelegalhelp.com/"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Divorce",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Support",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Adoption",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Custody",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Grand Parent's Rights",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>


<script>
    
function showDiv12() {
    $("#form32").show("1000");
	// document.getElementById('form32').style.display = "block";
    document.getElementById('btn1').style.display= "none";
 }

 function showDiv21() {
    // document.getElementById('form32').style.display = "none";
    $("#form32").hide("1000");
    $("#btn1").show("1000");
	// document.getElementById('btn1').style.display= "block";
 }

</script>


<script src="http://www.radioactivethinking.com/rateit/src/jquery.rateit.js"></script>


</head>


<body>

<?php include_once "header.php"; ?>
<?php 
$database=new Database();

$db = $database->getConnection();
            
if (isset($_POST['submitbtn']))
{
    $Name=$_POST['fname'];
    $Email=$_POST['email'];
    $Rating=$_POST['rating'];
    $Review=$_POST['review'];
    $Date=date("M d, Y");

    
     //write query
     $query = "INSERT INTO
            success_stories
    SET
    Name=:Name, Email=:Email, Rating=:Rating,  Review=:Review, Date=:Date";

    $stmt = $db->prepare($query);

    // posted values
    $Name=htmlspecialchars(strip_tags($Name));
    $Email=htmlspecialchars(strip_tags($Email));
    $Rating=htmlspecialchars(strip_tags($Rating));
    $Review=htmlspecialchars(strip_tags($Review));
    $Date=htmlspecialchars(strip_tags($Date));
    // bind values 
    $stmt->bindParam(":Name", $Name);
    $stmt->bindParam(":Email", $Email);
    $stmt->bindParam(":Rating", $Rating);
    $stmt->bindParam(":Review", $Review);
    $stmt->bindParam(":Date", $Date);
    if($stmt->execute()){
        // echo "succes";
        
          }else{

    }
}
    
    ?>


<div class="jumbotron jumbotron-fluid divorce_ser d-flex align-items-center border-0">
    <div class="container">

    <h1 class="jl_heading font-weight-bold text-white text-center" >CLIENT STORIES</h1>
    <h5 class="heading text-white text-center" >Happy Clients Comes After Lot of hard Work</br>Here is some reviews from our clients</h5>
    </div>
</div>

<div class="pl-4">
    <input type="button" class="btn btn-primary" value="Create your own review" onclick="showDiv12()" id="btn1"/>
</div>


<section class="container-fluid text-left text-dark mt-5" id="form32">

    <div class="col-lg-6 col-md-8 col-sm-12 col-12 d-block">
        <h6 class="text-dark font-weight-bold mb-2">Submit your review</h6>

        <form class="success_stories" method="post" >

            <div class="form-group mb-1">
                <label class="font-weight-bold mb-0 ml-1 mt-2" style="font-size:13px;">Name:</label>
                <input type="text" class="form-control p-3" name="fname" id="fname"  style="border-radius:0px;"/> 
            </div>

            <div class="form-group mb-1">
                <label class="font-weight-bold mb-0 ml-1 mt-2" style="font-size:13px;">Email:</label>
                <input type="text" class="form-control p-3" name="email" id="email" style="border-radius:0px;"/>
            </div>

            <div class="form-group mb-1">
                <label class="font-weight-bold mb-0 ml-1 mt-2" style="font-size:13px;">Rating:</label><br>
                <div class="stars text-left">
                    <input class="star star-5" id="star-5" type="radio" name="rating" value="5"/>
                    <label class="star star-5 mb-0" for="star-5"></label>

                    <input class="star star-4" id="star-4" type="radio" name="rating" value="4"/>
                    <label class="star star-4 mb-0" for="star-4"></label>

                    <input class="star star-3" id="star-3" type="radio" name="rating" value="3"/>
                    <label class="star star-3 mb-0" for="star-3"></label>

                    <input class="star star-2" id="star-2" type="radio" name="rating" value="2"/>
                    <label class="star star-2 mb-0" for="star-2"></label>

                    <input class="star star-1" id="star-1" type="radio" name="rating" value="1"/>
                    <label class="star star-1 mb-0" for="star-1"></label>
                </div>
            </div>

            <div class="form-group">
                <label class="font-weight-bold mb-0 ml-1 mt-2" style="font-size:13px;">Review:</label>
                <textarea class="form-control p-3" name="review" id="review" rows="8" cols="70" style="border-radius:0px;"></textarea>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Submit" name="submitbtn" class="btn btn-md btn-success mr-2 rounded-0"  />
                <input type="button" class="btn btn-secondary rounded-0" value="Cancel" onclick="showDiv21()"/>
            </div>
        </form>
    </div>
        
</section>


<div class="container-fluid mb-0 pb-0">
            
    <?php
        $database=new Database();
        $db = $database->getConnection();
        $sql = "SELECT * from  success_stories ";
        $query = $db -> prepare($sql);
        $query->execute();
    ?>
    <hr class="mt-4 ml-3 mr-3" style="border: 0.5px dashed #a2a2a2;" />
    <p class="font-weight-light font-italic text-dark mb-2 ml-3" style="font-size:12px; font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;">Affordable Legal Help</p>
    <p class="font-weight-light font-italic text-dark mb-2 ml-3" style="font-size:12px; font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;">Average rating:  <?php echo htmlentities($query->rowCount());?> reviews</p>

</div>

<div class="container-fluid mb-5">
        
    <table id="zctb" class="table table-white table-borderless p-0 m-0">

    <thead id="head1">
        <tr>
            <th class="text-white"> no use</th>
        </tr>
    </thead>
    <tbody>


        <?php
            $database=new Database();
            $db = $database->getConnection();

            $sql = "SELECT * from  success_stories ";
            $query = $db -> prepare($sql);
            $query->execute();
            $results=$query->fetchAll(PDO::FETCH_OBJ);
            $cnt=1;
            $opt="";
            if($query->rowCount() > 0)
            {
                foreach($results as $result)
                {		
        ?>	

        <tr>
            <td>
                <hr class="mt-4" style="border: 0.5px dashed #a2a2a2;" />

                <?php  
                    if ($result->Rating == 1 ) {
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                    } elseif ($result->Rating == 2) {
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                    } elseif ($result->Rating == 3) {
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                    }elseif ($result->Rating == 4) {
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='far fa-star text-warning inline-block'></i>"; 
                    }elseif ($result->Rating == 5) {
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                    }else {
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                        echo "<i class='fa fa-star text-warning inline-block'></i>"; 
                    }
                ?>
<!-- 
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="far fa-star text-warning inline-block"></i> -->

                <p class="font-weight-light font-italic text-dark mb-2" style="font-size:12px; display: inline-block; font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;"> <?php echo htmlentities($result->Date);?> by <?php echo htmlentities($result->Name);?> on Affordable Legal Help</p>
                
                <div class="card border-right-0 border-top-0 border-bottom-0 rounded-0" style="border-left: 5px solid rgba(222, 222, 222);" >
                    <div class="card-body pt-3 pb-3">
                        <p class="card-text text-black-50" style="font-size:14px; font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;"><?php echo htmlentities($result->Review);?></p>
                    </div>
                </div>
            </td>
        </tr>
        <?php }} ?>
        <!-- <tr>
            <td>
                <hr class="mt-4" style="border: 0.5px dashed #a2a2a2;" />


                <i class="fa fa-star text-warning inline-block"></i>
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="fa fa-star text-warning inline-block"></i>
                <i class="far fa-star text-warning inline-block"></i>

                <p class="font-weight-light font-italic text-dark mb-2" style="font-size:12px; display: inline-block; font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;">Nov 26, 2019 by Daniel Rivas on Affordable Legal Help</p>
                
                <div class="card border-right-0 border-top-0 border-bottom-0 rounded-0" style="border-left: 5px solid rgba(222, 222, 222);" >
                    <div class="card-body pt-3 pb-3">
                        <p class="card-text text-black-50" style="font-size:14px; font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif;">Going through formal proceedings of filing divorce is extremely frustrating. Highly skilled unbundled lawyers under Affordable legal Help will ensure that your goals and demands are met without breaking your bank.</p>
                    </div>
                </div>
            </td>
        </tr> -->

        

    </tbody>
    </table>
</div>



<?php include_once "footer.php"; ?>




<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>

<script>
// $(document).ready(function() {
//     $('#zctb').DataTable({
//         "paging": true,
// 		"pagingType":"full_numbers",
// 		"lengthMenu":[[-1,15,25,50],['All',15,25,50]],
// 		responsive:true,
//         stateSave: true,
        
//         "paging":   false,
//         "ordering": false,
//         "info":     false
// 	});
	
// });

// $(document).ready( function () {
//   $('#zctb').DataTable(
//     { language: {
//         searchPlaceholder: "Search records",
//         search: "",
//       }
//     })

// } );

$(document).ready(function() {
    $('#zctb').DataTable( {
        "lengthChange": false,
        "bFilter": false,
        "dom": 'lrtip'
    } );
} );

</script>


</body>
</html>
