
<?php include("libs.php");
include("config/connect.php");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
    
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />
    <!--yandex-->
    <meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<title>Our Blogs | Find Affordable Legal Help with us </title>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />

<meta name="description" content="Enjoy Fast Access To Top Family Lawyers Across The US. Connect Now With An Attorney In Your Local Area And Get Your Questions Answered Now.">


<?php include "libs.php"; ?>


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "FIND The Right Family Lawyer In Your Zip Code",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png",
  "url" : "https://affordablelegalhelp.com/"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Divorce",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Support",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Adoption",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Custody",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Grand Parent's Rights",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>
</head>
		

<body class="fontb">
<?php
include"header.php";
?>

<div class="jumbotron jumbotron-fluid bg1 blog_bg border-0">
    <div class="paddings">
        <h1 class="size46 text-white text-center ">OUR BLOGS</h1>
    </div>
</div>

<div id="searchbox" class="container border-light border-top border-bottom border-right border-left mt-4 p-3 d-block" style="box-shadow:0px 0px 11px 0px #CCCCCC;">
    
    <form action="blog-search-result" method="get" enctype="multipart/form-data">
        <p class="font-weight-bold text-left texts">Search Article</p>
        <div class="row">
            <input type="text" class="form-control col-8 col-lg-9 col-md-9 col-sm-9 mt-0 pt-0 mr-1 ml-2" name="value" placeholder="Search this site" size="25">
            <input type="submit" name="search" class="btn btn-primary col-3 col-lg-2 col-md-2 col-sm-2" value="Search">
        </div>
    </form>
</div>

<section class="bg-transparent text-dark mt-5">
<div class="container">
    <div class="row">
        
        <div class="col-xl-8 col-lg-8 col-md-8  col-sm-12 col-12  mb-3" >
           
        	<?php 
            // include("config/connect.php");
            $select_posts = "select * from posts order by rand() LIMIT 0,4";
            $run_posts = mysqli_query($con,$select_posts);
            while($row=mysqli_fetch_array($run_posts)){
                $post_id = $row['post_id']; 
                $post_title = $row['post_title'];
                $post_date = $row['post_date'];
                $post_author = $row['post_author'];
                $post_image = $row['post_image'];
                $post_content = $row['post_content'];
            ?>
            
             <div class="card bg-white set_img card h-100 mb-5 " style="border-radius:20px; box-shadow:0px 0px 8px 0px #CCCCCC;">
                <div class="card-body text-dark">
                	<a href="view-blog/<?php echo $post_id; ?>" class="nav-link text-dark pl-0 ml-0">
                    <h2 onmouseover="this.style.color='#959595';" onmouseout="this.style.color='black';">
                    <?php echo $post_title; ?>
                    </h2>
                    </a>
                    
                    
                    <!--<p class="text-black-50 text-left" style="font-size:15px; font-weight:500;">-->
                        <?php
                        // echo $post_date;
                        ?>
                        <!--</p>-->
                    
                    <!--<p align="right">Posted by:&nbsp;&nbsp;<b>-->
                    <?php
                     //echo $post_author; 
                     
                     ?>
                     <!--</b></p>-->
                    
                    <img src="/images/<?php echo $post_image; ?>" class="img-fluid"/>
                    <?php
                    // for ($i=0;$i<300;$i++){
                    //     echo $post_content[$i];
                    // }
                    $post_content=strip_tags($post_content);
                    $post_content=substr($post_content,0,300);
                    ?>
                    <p  class="text-dark fontb text-left pt-3 ">
                    <?php 
                    
                    // echo implode(' ', array_slice(explode(' ', $gg), 0, 90));
                    // echo $post_content;
                        echo "<p class='card-text text-secondary text-left size15 decor' >$post_content...</p>";
                    ?>
                    </p>
                    
                    <p align="right"><a href="view-blog/<?php echo $post_id; ?>" class="btn btn-md font-weight-normal btn-outline-danger mt-2 mr-2" >
                        Continue Reading <i class="fas fa-chevron-right "></i>
                    </a></p>
                </div>
            </div>
            <?php } ?>
                	 
        </div>
        
        <div class="col-xl-4 col-lg-4 col-md-4  col-sm-12 col-12 mb-3 ">
            <div class="card  bg-white set_img  card h-100 " style="display: table-cell; box-shadow:0px 0px 15px 0px #CCCCCC;">
                <div class="card-body text-dark">
                	
                	<h2 align="left">Recently Uploaded</h2><hr>
                    <?php 
                    
                    $query = "select * from posts order by 1 DESC LIMIT 0,6";
                    
                        $run = mysqli_query($con,$query); 
                        
                        while ($row=mysqli_fetch_array($run)){
                        
                        $post_id = $row['post_id'];
                        $title = $row['post_title'];
                        $image = $row['post_image'];
                        $post_date = $row['post_date'];
                    
                    ?>
                        <div class="row mt-2 p-2">
                            <a href="view-blog/<?php echo $post_id; ?>" class="col-5 d-block mr-0 pr-0">
                            <img src='/images/<?php echo $image; ?>' width='100' height='100'></a>
                            
                            <a href="view-blog/<?php echo $post_id; ?>" class="col-7 d-block ml-0 pl-0 pr-0 text-dark nav-link" >
                            <h5 class="font-weight-normal" onmouseover="this.style.color='#959595';" onmouseout="this.style.color='black';">
                            <?php echo $title; ?></h5>
                            <!--<p class="text-left text-black-50">&nbsp;&nbsp;<b>-->
                            <?php
                            // echo $post_date;
                            ?>
                            <!--</b></p>-->
                            </a>
                        
                        </div>
                        
                        
                    <?php } ?>
                	
                </div>
            </div>
        </div>

        
    </div>
</div>
</section>




<?php include("footer.php"); ?>





<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>


<?php include "libs2.php"; ?>
<script defer src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>



</body>
</html>