<?php 
session_start();
error_reporting(0);
include_once "config/database.php"; 
include_once "object/login.php";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="8B265896C88DF7D5ADC560D97D5B8052" />
    <!--yandex-->
    <meta name="yandex-verification" content="0beccc11dc0dc9cb" />
<title>Frequently Ask Questions | Find Affordable Legal Help with us </title>
<link rel="shortcut icon" type="image/x-icon" href="favicon.png" />

<meta name="description" content="Enjoy Fast Access To Top Family Lawyers Across The US. Connect Now With An Attorney In Your Local Area And Get Your Questions Answered Now.">
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=yes">
<!--#Libraries file#-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>


<link href='https://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>

<?php include "libs.php"; ?>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>-->
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" />-->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" /> -->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->

<!--<script async src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>-->
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />-->





<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142213622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142213622-3');
</script>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable Legal Help",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "FIND The Right Family Lawyer In Your Zip Code",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png",
  "url" : "https://affordablelegalhelp.com/"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Divorce",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Support",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Adoption",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Child Custody",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Grand Parent's Rights",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Affordable",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp.png"
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "image" : "https://affordablelegalhelp.com/Image/legalHelp_footer.png"
} ]
</script>
</head>



<body class="font2">
    
<?php include_once "header.php"; ?>

<div class="jumbotron jumbotron-fluid bg1 stories_bg d-flex align-items-center border-0">
    <div class="container">
        <h1 class="size46 font-weight-normal text-white text-left font1">Frequently Ask Questions</h1>
        <hr align="left" class="m-0 col-5 col-lg-5 col-md-4 col-sm-4" style="border: 3px solid rgba(0, 81, 152); border-radius: 2px;" />
    </div>
</div>


<div class="container mb-5 mt-5">

    <div class="row">

        <div class="col-xl-6 col-lg-6  col-md-12 col-sm-12 col-12  p-4 d-flex">
            <div class="card border-0 bg-white flex-fill" style="box-shadow: 0px 0px 5px 0px #CCCCCC;">

                <div class="card-body">
                    <div class="card-title">
                        <h5 class="font-weight-normal text-left size20">
                            How Unbundled Legal Services Benefit Divorce Cases?
                        </h5>
                    </div>
                    <p class="card-text text-black-50 text-left size16">
                        Going through a divorce is a challenging, painful, transforming, and expensive experience.  It is not something that anyone wants to go through but there are times when it becomes necessary in order to end a failed, sometimes even abusive, marriage and move on.  Depending on factors like the money and property involved, disputes over custody of children, and the attitude of the parties, it can be a long, messy process...
                    </p>
                </div>
            </div>
        </div>

        <div class="col-xl-6 col-lg-6  col-md-12 col-sm-12 col-12  p-4 d-flex">
            <div class="card border-0 bg-white flex-fill" style="box-shadow: 0px 0px 5px 0px #CCCCCC;">

                <div class="card-body">
                    <div class="card-title">
                        <h5 class="font-weight-normal text-left size20">
                            How Unbundled Legal Services Benefit Divorce Cases?
                        </h5>
                    </div>
                    <p class="card-text text-black-50 text-left size16">
                        Going through a divorce is a challenging, painful, transforming, and expensive experience.  It is not something that anyone wants to go through but there are times when it becomes necessary in order to end a failed, sometimes even abusive, marriage and move on.  Depending on factors like the money and property involved, disputes over custody of children, and the attitude of the parties, it can be a long, messy process...
                    </p>
                </div>
            </div>
        </div>

        <div class="col-xl-6 col-lg-6  col-md-12 col-sm-12 col-12  p-4 d-flex">
            <div class="card border-0 bg-white flex-fill" style="box-shadow: 0px 0px 5px 0px #CCCCCC;">

                <div class="card-body">
                    <div class="card-title">
                        <h5 class="font-weight-normal text-left size20">
                            How Unbundled Legal Services Benefit Divorce Cases?
                        </h5>
                    </div>
                    <p class="card-text text-black-50 text-left size16">
                        Going through a divorce is a challenging, painful, transforming, and expensive experience.  It is not something that anyone wants to go through but there are times when it becomes necessary in order to end a failed, sometimes even abusive, marriage and move on.  Depending on factors like the money and property involved, disputes over custody of children, and the attitude of the parties, it can be a long, messy process...
                    </p>
                </div>
            </div>
        </div>

        <div class="col-xl-6 col-lg-6  col-md-12 col-sm-12 col-12  p-4 d-flex">
            <div class="card border-0 bg-white flex-fill" style="box-shadow: 0px 0px 5px 0px #CCCCCC;">

                <div class="card-body">
                    <div class="card-title">
                        <h5 class="font-weight-normal text-left size20">
                            How Unbundled Legal Services Benefit Divorce Cases?
                        </h5>
                    </div>
                    <p class="card-text text-black-50 text-left size16">
                        Going through a divorce is a challenging, painful, transforming, and expensive experience.  It is not something that anyone wants to go through but there are times when it becomes necessary in order to end a failed, sometimes even abusive, marriage and move on.  Depending on factors like the money and property involved, disputes over custody of children, and the attitude of the parties, it can be a long, messy process...
                    </p>
                </div>
            </div>
        </div>


    </div>
</div>





<?php include_once"footer.php"; ?>


</body>
</html>

